// Generated by gencpp from file can_ros/send_can.msg
// DO NOT EDIT!


#ifndef CAN_ROS_MESSAGE_SEND_CAN_H
#define CAN_ROS_MESSAGE_SEND_CAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace can_ros
{
template <class ContainerAllocator>
struct send_can_
{
  typedef send_can_<ContainerAllocator> Type;

  send_can_()
    : header()
    , send_steering_r1(0.0)
    , send_steering_l1(0.0)
    , send_steering_r2(0.0)
    , send_steering_l2(0.0)
    , send_steering_r3(0.0)
    , send_steering_l3(0.0)
    , send_throttle_r(0.0)
    , send_throttle_l(0.0)  {
    }
  send_can_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , send_steering_r1(0.0)
    , send_steering_l1(0.0)
    , send_steering_r2(0.0)
    , send_steering_l2(0.0)
    , send_steering_r3(0.0)
    , send_steering_l3(0.0)
    , send_throttle_r(0.0)
    , send_throttle_l(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _send_steering_r1_type;
  _send_steering_r1_type send_steering_r1;

   typedef double _send_steering_l1_type;
  _send_steering_l1_type send_steering_l1;

   typedef double _send_steering_r2_type;
  _send_steering_r2_type send_steering_r2;

   typedef double _send_steering_l2_type;
  _send_steering_l2_type send_steering_l2;

   typedef double _send_steering_r3_type;
  _send_steering_r3_type send_steering_r3;

   typedef double _send_steering_l3_type;
  _send_steering_l3_type send_steering_l3;

   typedef double _send_throttle_r_type;
  _send_throttle_r_type send_throttle_r;

   typedef double _send_throttle_l_type;
  _send_throttle_l_type send_throttle_l;





  typedef boost::shared_ptr< ::can_ros::send_can_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_ros::send_can_<ContainerAllocator> const> ConstPtr;

}; // struct send_can_

typedef ::can_ros::send_can_<std::allocator<void> > send_can;

typedef boost::shared_ptr< ::can_ros::send_can > send_canPtr;
typedef boost::shared_ptr< ::can_ros::send_can const> send_canConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_ros::send_can_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_ros::send_can_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::can_ros::send_can_<ContainerAllocator1> & lhs, const ::can_ros::send_can_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.send_steering_r1 == rhs.send_steering_r1 &&
    lhs.send_steering_l1 == rhs.send_steering_l1 &&
    lhs.send_steering_r2 == rhs.send_steering_r2 &&
    lhs.send_steering_l2 == rhs.send_steering_l2 &&
    lhs.send_steering_r3 == rhs.send_steering_r3 &&
    lhs.send_steering_l3 == rhs.send_steering_l3 &&
    lhs.send_throttle_r == rhs.send_throttle_r &&
    lhs.send_throttle_l == rhs.send_throttle_l;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::can_ros::send_can_<ContainerAllocator1> & lhs, const ::can_ros::send_can_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace can_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::can_ros::send_can_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_ros::send_can_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_ros::send_can_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_ros::send_can_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_ros::send_can_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_ros::send_can_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_ros::send_can_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b15c8135f18b0c409bca56dccddaa0d9";
  }

  static const char* value(const ::can_ros::send_can_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb15c8135f18b0c40ULL;
  static const uint64_t static_value2 = 0x9bca56dccddaa0d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::can_ros::send_can_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_ros/send_can";
  }

  static const char* value(const ::can_ros::send_can_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_ros::send_can_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 send_steering_r1\n"
"float64 send_steering_l1\n"
"float64 send_steering_r2\n"
"float64 send_steering_l2\n"
"float64 send_steering_r3\n"
"float64 send_steering_l3\n"
"float64 send_throttle_r\n"
"float64 send_throttle_l\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::can_ros::send_can_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_ros::send_can_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.send_steering_r1);
      stream.next(m.send_steering_l1);
      stream.next(m.send_steering_r2);
      stream.next(m.send_steering_l2);
      stream.next(m.send_steering_r3);
      stream.next(m.send_steering_l3);
      stream.next(m.send_throttle_r);
      stream.next(m.send_throttle_l);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct send_can_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_ros::send_can_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_ros::send_can_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "send_steering_r1: ";
    Printer<double>::stream(s, indent + "  ", v.send_steering_r1);
    s << indent << "send_steering_l1: ";
    Printer<double>::stream(s, indent + "  ", v.send_steering_l1);
    s << indent << "send_steering_r2: ";
    Printer<double>::stream(s, indent + "  ", v.send_steering_r2);
    s << indent << "send_steering_l2: ";
    Printer<double>::stream(s, indent + "  ", v.send_steering_l2);
    s << indent << "send_steering_r3: ";
    Printer<double>::stream(s, indent + "  ", v.send_steering_r3);
    s << indent << "send_steering_l3: ";
    Printer<double>::stream(s, indent + "  ", v.send_steering_l3);
    s << indent << "send_throttle_r: ";
    Printer<double>::stream(s, indent + "  ", v.send_throttle_r);
    s << indent << "send_throttle_l: ";
    Printer<double>::stream(s, indent + "  ", v.send_throttle_l);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_ROS_MESSAGE_SEND_CAN_H
